#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg=$(git rev-list --format=%B --max-count=1 HEAD | tail +2)

semantic_version=$(npm pkg get version | cut -d'"' -f 2)

if [[ $(echo "$commit_msg" | grep "RUN_RECOMMIT_MINOR") != "" ]]; then
  line_number=$(echo "$commit_msg" | grep -n RUN_RECOMMIT_MINOR | awk '{print $1}' FS=":")
  commit_msg=$(echo "$commit_msg" | sed "${line_number}d")
  echo "git reset --soft HEAD~"
  git reset --soft HEAD~
  yarn version --minor --no-git-tag-version
elif [[ $(echo "$commit_msg" | grep "RUN_RECOMMIT_PATCH") != "" ]]; then
  line_number=$(echo "$commit_msg" | grep -n RUN_RECOMMIT_PATCH | awk '{print $1}' FS=":")
  commit_msg=$(echo "$commit_msg" | sed "${line_number}d")
  echo "git reset --soft HEAD~"
  git reset --soft HEAD~
  yarn version --patch --no-git-tag-version
else
  exit 0
fi

# stage files
echo "stage files"
git add package.json

echo "git commit"
git commit -m "${commit_msg}" --no-verify

if [[ $(npm pkg get version | cut -d'"' -f 2) != $semantic_version ]]; then
  git tag "v$(npm pkg get version | cut -d'"' -f 2)"
else
  exit 0
fi
